apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: doraemon-api
  name: doraemon-api
  namespace: default
data:
  app.conf: |-
    appname = doraemon
    httpport = 8080
    runmode = dev
    autorender = false
    copyrequestbody = true
    sessionon = true
    EnableDocs = true
    # mysql
    DBName = "doraemon"
    DBTns = "tcp(mysql-doraemon:3306)"
    DBUser = "root"
    DBPasswd = "root"
    DBLoc = "Asia%2FShanghai"
    DBConnTTL = 30

    SmsUrl="http://10.202.209.8:20499/api/v1/sms"
    LanxinUrl="http://10.202.209.8:20499/api/v1/lanxin/text"
    CallUrl="http://10.202.209.8:20499/api/v1/lanxin/call"
    DutyGroupUrl="http://monitor.corp.qihoo.net/Api/getDutyUser"
    BrokenUrl="http://stree.io/api/hosts/broken"
    WebUrl="http://doraemon.qihoo.cloud"

    # oauth2
    [auth.oauth2]
    auth_url = "https://example.com/oauth2/v1/authorize"
    client_id="jjU7RxweGqtpZFzyOO03nJLonoJTLBXl"
    client_secret="keV1NONheo8AtIX0DPvQFK4pUl3AF4Se"
    token_url = "https://krypto.qihoo.cloud/oauth2/v1/token"
    api_url ="https://krypto.qihoo.cloud/oauth2/v1/userinfo"

    # ldap config
    [auth.ldap]
    enabled = false
    ldap_url = ldap://127.0.0.1
    ldap_search_dn = "cn=admin,dc=example,dc=com"
    ldap_search_password = admin
    ldap_base_dn = "dc=example,dc=com"
    ldap_filter =
    ldap_uid = cn
    ldap_scope = 2
    ldap_connection_timeout = 30

---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: doraemon-ui
  name: doraemon-ui
  namespace: default
data:
  config.js: |-
    window.CONFIG = {
      baseURL: 'http://nodeip:32000',
    };

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: doraemon-web
  labels:
    app: doraemon-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doraemon-web
  template:
    metadata:
      labels:
        app: doraemon-web
    spec:
      volumes:
        - name: config
          configMap:
            name: doraemon-api
        - name: ui-config
          configMap:
              name: doraemon-ui
              items:
                - key: config.js
                  path: config.js
      containers:
        - resources:
            limits:
              memory: 1Gi
              cpu: '1'
            requests:
              memory: 1Gi
              cpu: '0.5'
          env: []
          envFrom: []
          imagePullPolicy: Always
          name: alertgateway
          image: 'r.qihoo.cloud/infra/alert-gateway:latest'
          command:
            - ./doraemon
          volumeMounts:
            - name: config
              mountPath: /opt/doraemon/conf/
        - resources:
            limits:
              memory: 1Gi
              cpu: '1'
            requests:
              memory: 1Gi
              cpu: '0.5'
          env: []
          envFrom: []
          imagePullPolicy: Always
          name: alertgateway-fe
          image: 'r.qihoo.cloud/infra/doraemon-frontend:latest'
          volumeMounts:
            - name: ui-config
              mountPath: /usr/local/openresty/nginx/html/config.js
              subPath: config.js

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: doraemon-web
  name: doraemon-web
  namespace: default
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: doraemon-web