apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-doraemon
  namespace: default
  labels:
    app: mysql-doraemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-doraemon
  template:
    metadata:
      labels:
        app: mysql-doraemon
    spec:
      containers:
        - name: mysql
          image: 'mysql:5.6.41'
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-doraemon
  name: mysql-doraemon
  namespace: default
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-doraemon
